define([], function() {
  return {
    "userLang": "en-us",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "altImgLogo":"Logo of",
    "seeAll":"See all",
    "seeAllLabel": "See all of my communities",
    "seeAllToggle": "This webpart is for the see all page",
    "seeAllOn" :"Yes",
    "seeAllOff" : "No",
    "setPageNum": "Number per page",
    "setLayoutOpt": "Layout option",
    "setSortOpt" : "sort option",
    "gridIcon" : "Grid",
    "compactIcon" : "Compact",
    "listIcon" : "List",
    "alphabetical": "Alphabetical",
    "dateCreation" : "Creation date",
    "loadingState" : "Loading",
    "pagPrev" : "Previous",
    "pagNext" : "Next",
    "firstPage" : "First",
    "lastPage" : "Last",
    "currentPage" : "Current Page",
    "goToPage": "Go to page",
    "groups" : "Group",
    "noResults": "Sorry.\n We couldn't find the community you were looking for.\n Either the community does not exist, or it has a different name.\n Try searching for the community by another letter in the title \n or start your own community.",
    "members": "Members",
    "siteViews": "Views",
    "created": "Created",
    "lastModified": "Last modified",
    "hidingYeti": "Hiding yeti",
    "setTitleEn": "Title in english",
    "setTitleFr": "Title in french",
    "sorry": "Sorry.",
    "We_couldnt_find": "We couldn't find the community you were looking for.",
    "Does_not_exist": " Either the community does not exist or it has a different name.",
    "Try_searching":"Try searching for the community by another letter in the title or start your own community.",

    
  }
});