define([], function() {
    return {
      "userLang": "fr-fr",
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Group Name",
      "DescriptionFieldLabel": "Description Field",
      "userLang": "fr-fr",
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Group Name",
      "DescriptionFieldLabel": "Description Field",
      "altImgLogo": "Logo de",
      "pagPrev": "Précédant",
      "pagNext": "Suivant",
      "firstPage" : "Premiere",
      "lastPage" : "Derniere",
      "currentPage" : "Page en cours",
      "setPageNum": "Nombre par page",
      "setLayoutOpt": "Option de mise en page",
      "setSortOpt": "Option de tri",
      "gridIcon": "Grille",
      "compactIcon": "Compacte",
      "dateCreation": "Date de création",
      "alphabetical": "Alphabétique",
      "groups": "collectivités",
      "seeAll":"Afficher tout",
      "seeAllLabel": "Afficher toutes mes collectivités",
      "listIcon": "Liste",
      "seeAllToggle": "Ce webpart est pour la page Afficher tout",
      "seeAllOn": "Oui",
      "seeAllOff": "Non",
      "loadingState": "Chargement en cours",
      "noResults": "Désolés.\n Nous ne pouvons trouver la collectivité que vous cherchez.\n Soit elle n’existe pas ou elle porte un autre nom que celui que vous avez entré.\nEssayez de trouver cette collectivité en utilisant un autre caractère qui fait partie du titre ou créez votre propre collectivité.",
      "members": "Membres ",
      "siteViews": "Vues ",
      "created": "Créé ",
      "lastModified": "Dernière modification ",
      "hidingYeti": "Un yeti caché",
      "goToPage": "Aller à la page",
      "setTitleEn": "Titre en anglais",
      "setTitleFr": "Titre en français",
      "sorry": "Désolés.",
      "We_couldnt_find": "Nous ne pouvons trouver la collectivité que vous cherchez.",
      "Does_not_exist": "Soit elle n’existe pas ou elle porte un autre nom que celui que vous avez entré.",
      "Try_searching":"Essayez de trouver cette collectivité en utilisant un autre caractère qui fait partie du titre ou créez votre propre collectivité.",
      "createComm": "Créez une collectivité",
      "createCommLink": "Lien pour créer une collectivité",
      "user_not_in_communities": "",
  
    }
  });